tasks:
  - init: |
      # Download Anaconda installer
      wget https://repo.anaconda.com/archive/Anaconda3-2024.02-1-Linux-x86_64.sh
      # Install Anaconda in batch mode
      bash Anaconda3-2024.02-1-Linux-x86_64.sh -b -p $HOME/anaconda3
      # Clean up installer
      rm Anaconda3-2024.02-1-Linux-x86_64.sh
      # Initialize conda for bash
      $HOME/anaconda3/bin/conda init bash
      # Update conda
      $HOME/anaconda3/bin/conda update -n base -c defaults conda -y
    command: |
      # Activate conda for this session
      source $HOME/anaconda3/bin/activate
      conda activate base
      echo "Anaconda is ready! Type 'conda --version' to verify."