tasks:
  - init: |
      # Download Anaconda installer
      wget https://repo.anaconda.com/archive/Anaconda3-2024.02-1-Linux-x86_64.sh
      # Install Anaconda in batch mode
      bash Anaconda3-2024.02-1-Linux-x86_64.sh -b -p $HOME/anaconda3
      # Clean up installer
      rm Anaconda3-2024.02-1-Linux-x86_64.sh
      # Initialize conda for bash
      $HOME/anaconda3/bin/conda init bash
      # Create virtual environment
      source $HOME/anaconda3/bin/activate
      conda create -n myenv python=3.11 -y
      conda activate myenv
      # Install common packages
      conda install numpy pandas matplotlib jupyter scikit-learn -y
    command: |
      # Activate the virtual environment automatically
      source $HOME/anaconda3/bin/activate
      conda activate myenv
      echo "✅ Anaconda virtual environment 'myenv' is ready!"
      echo "Python version: $(python --version)"